dist: trusty
language: php
sudo: false

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction

script:
    - vendor/bin/phpcs --standard=PSR2 --extensions=php --encoding=utf-8 --ignore=*/vendor/* . -p
    - vendor/bin/phpunit